// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxrDMfiMxJUHUVDOCtup8R8hF3RpnQrNs',
    appId: '1:665275834391:web:bf940bce95994246243c52',
    messagingSenderId: '665275834391',
    projectId: 'movies-app-17f9e',
    authDomain: 'movies-app-17f9e.firebaseapp.com',
    storageBucket: 'movies-app-17f9e.firebasestorage.app',
    measurementId: 'G-JMEXGCCXDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjICl0pDm7NkFqpzhT_emcT21-c-XZMYA',
    appId: '1:665275834391:android:8366bc75bb3d6bec243c52',
    messagingSenderId: '665275834391',
    projectId: 'movies-app-17f9e',
    storageBucket: 'movies-app-17f9e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmtNKLGEu2PaZsp1C6ITG9HzHt-hG_kuc',
    appId: '1:665275834391:ios:7e49b01f7b1b8305243c52',
    messagingSenderId: '665275834391',
    projectId: 'movies-app-17f9e',
    storageBucket: 'movies-app-17f9e.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmtNKLGEu2PaZsp1C6ITG9HzHt-hG_kuc',
    appId: '1:665275834391:ios:7e49b01f7b1b8305243c52',
    messagingSenderId: '665275834391',
    projectId: 'movies-app-17f9e',
    storageBucket: 'movies-app-17f9e.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxrDMfiMxJUHUVDOCtup8R8hF3RpnQrNs',
    appId: '1:665275834391:web:901af84cd8e049bc243c52',
    messagingSenderId: '665275834391',
    projectId: 'movies-app-17f9e',
    authDomain: 'movies-app-17f9e.firebaseapp.com',
    storageBucket: 'movies-app-17f9e.firebasestorage.app',
    measurementId: 'G-27C0VPTG20',
  );
}
